on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  repository_dispatch:

name: renderbook

jobs:
  bookdown:
    name: Render-Book
    runs-on: macOS-latest

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          
      - name: Setup R
        uses: r-lib/actions/setup-r@v1

      - name: Install pandoc and jags
        run: |
          brew install pandoc
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "blogdown", "devtools"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Install hugo
        run: |
          Rscript -e 'blogdown::install_hugo(version = "0.59.0")'
      - name: Build training site
        run: |
              Rscript -e 'blogdown::build_site()'
              sh _build_and_merge.sh
              touch public/.nojekyll
              cp CNAME public/CNAME
              
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: public # The folder the action should deploy.