on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
  repository_dispatch:
    types: [quarto, bookdown]

name: renderbook

env:
  BRANCH: '2023-08-delta' # must be set

jobs:

  quarto:
    if: github.event.action == 'quarto' || github.event.action == 'bookdown' || github.event_name == 'push'
    runs-on: ubuntu-latest
    
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3
        with:
            submodules: true

      - name: Make nceas-training repo accessible as a temp dir 
        uses: actions/checkout@v3
        with:
            repository: NCEAS/nceas-training
            ref: "${{ env.BRANCH }}"
            path: nceas-training

      - uses: Homebrew/actions/setup-homebrew@master

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          
      - name: System libraries
        run: |
          sudo apt-get install -y libjq-dev libudunits2-dev libpoppler-cpp-dev libgdal-dev gdal-bin libproj-dev proj-data proj-bin libgeos-dev librdf0-dev libharfbuzz-dev libfribidi-dev
        
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
      
      - name: Restore R package cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.R_LIBS_USER }}/*
          key: ${{ runner.os }}-build-R-${{ hashFiles('**/DESCRIPTION') }}

      - name: Install R dependencies
        run: |
          options(repos = c(REPO_NAME = "https://packagemanager.posit.co/cran/__linux__/jammy/latest"))
          install.packages(c("remotes"))
          remotes::install_deps()
          remotes::install_deps(pkgdir="nceas-training/materials")
        shell: Rscript {0}

      - name: Install pandoc
        run: |
          brew install pandoc

      - name: Install hugo
        run: |
          Rscript -e 'blogdown::install_hugo(version = "0.59.0")'
          
      - name: Build blogdown site
        run: |
              Rscript -e 'blogdown::build_site()'
              touch public/.nojekyll
              cp CNAME public/CNAME

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/install-quarto@v1
        
      - name: Install tinytex
        run: quarto install tool tinytex
        
      #- name: Build training materials scalable
       # run: sh _build_quarto.sh
      
      - name: Render Quarto nceas-training
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: html
          path: nceas-training/materials # build from nceas-training from temp dir
      
      - name: Move training materials to public/$BRANCH
        run: |
          mkdir -p public/$BRANCH # make dir if none exists
          cp -R nceas-training/materials/_book public/$BRANCH 
        
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: public/ # The folder the action should deploy.
   
  bookdown:
    if: github.event.action == 'test' 
    runs-on: macOS-latest
    
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          
      - uses: Homebrew/actions/setup-homebrew@master
          
      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install pandoc
        run: |
          brew install pandoc
          
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "blogdown", "devtools"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Install hugo
        run: |
          Rscript -e 'blogdown::install_hugo(version = "0.59.0")'
          
      - name: Build blogdown site
        run: |
              Rscript -e 'blogdown::build_site()'
              touch public/.nojekyll
              cp CNAME public/CNAME

      - uses: quarto-dev/quarto-actions/setup@v2
        
      - name: Build training materials
        run: sh _build_bookdown.sh
        
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
            branch: gh-pages # The branch the action should deploy to.
            folder: public/ # The folder the action should deploy.        
        
