on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  repository_dispatch:
    types: [quarto, bookdown]

name: renderbook

jobs:
  blogdown:
    name: Build-Site
    runs-on: macOS-latest

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          
      - name: Setup R
        uses: r-lib/actions/setup-r@v1

      - name: Install pandoc
        run: |
          brew install pandoc
          
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "blogdown", "devtools"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Install hugo
        run: |
          Rscript -e 'blogdown::install_hugo(version = "0.59.0")'
          
      - name: Build blogdown site
        run: |
              Rscript -e 'blogdown::build_site()'
              touch public/.nojekyll
              cp CNAME public/CNAME

  quarto:
      if: github.event_name == "quarto"
      steps:
      runs-on: ubuntu-latest
      - name: "Install Quarto"

        uses: quarto-dev/quarto-actions/install-quarto@v1

      - name: "Install tinytex"
        run: quarto install tool tinytex
        
      - name: Build training materials
        run: sh _build_quarto.sh
        
  bookdown:
    if: github.event_name == "bookdown"
    runs-on: ubuntu-latest
    steps:
      - name: Build training site
        run: sh _build_bookdown.sh
        
  deploy:
    runs-on: ubuntu-latest
    steps:       
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: public # The folder the action should deploy.