on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  repository_dispatch:
    types: [quarto, bookdown]

name: renderbook

jobs:

  quarto:
    if: github.event.action == 'quarto' || github.event.action == 'bookdown' || github.event_name == 'push'
    runs-on: ubuntu-latest
    
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          
      - uses: Homebrew/actions/setup-homebrew@master

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
      
      - name: Install libjq
        run: |
          sudo apt-get install -y libjq-dev
          sudo apt-get install -y libudunits2-dev 
          sudo apt-get install -y libpoppler-cpp-dev
          sudo apt-get install libgdal-dev gdal-bin libproj-dev proj-data proj-bin libgeos-dev
        
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          extra-packages: |
            any::remotes
            any::blogdown
            any::devtools

      - name: Install pandoc
        run: |
          brew install pandoc

      - name: Install hugo
        run: |
          Rscript -e 'blogdown::install_hugo(version = "0.59.0")'
          
      - name: Build blogdown site
        run: |
              Rscript -e 'blogdown::build_site()'
              touch public/.nojekyll
              cp CNAME public/CNAME

      - name: "Install Quarto"
        uses: quarto-dev/quarto-actions/install-quarto@v1
        
      - name: "Install tinytex"
        run: quarto install tool tinytex
        
      #- name: Build training materials scalable
       # run: sh _build_quarto.sh
        
      - name: Build training materials learning-hub
        run: sh _build_bookdown.sh
        
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: public/ # The folder the action should deploy.
   
  bookdown:
    if: github.event.action == 'test' 
    runs-on: macOS-latest
    
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          
      - uses: Homebrew/actions/setup-homebrew@master
          
      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install pandoc
        run: |
          brew install pandoc
          
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "blogdown", "devtools"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Install hugo
        run: |
          Rscript -e 'blogdown::install_hugo(version = "0.59.0")'
          
      - name: Build blogdown site
        run: |
              Rscript -e 'blogdown::build_site()'
              touch public/.nojekyll
              cp CNAME public/CNAME

      - uses: quarto-dev/quarto-actions/setup@v2
        
      - name: Build training materials
        run: sh _build_bookdown.sh
        
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: public/ # The folder the action should deploy.        
        
